name=MyRP_Pico2_mini_BNO086
version=1.0.0
author=Phichaiyut Deesungnern
maintainer=Phichaiyut Deesungnern <phichaiyut.d@gmail.com>
sentence=Robot library for RP2350 Pico2 mini with BNO086 IMU, motors, servos, buzzer, MCP3008 sensors and PID line/gyro control.
paragraph=Includes BNO08x gyro heading, MCP3008 line sensors, motor and servo drivers, buzzer, battery monitor and PID helpers.
category=Device Control
url=https://github.com/phichaiyut/MyRP_Pico2_Mini_BNO086
architectures=rp2040
includes=MyRP_Pico2_mini_BNO086.h
depends=SparkFun BNO080 Cortex Based IMU
